# ansible
ansible_user: ubuntu
ansible_ssh_private_key_file: /Users/david/.ssh/id_ansible
# setup
user_name: david
github_user: konstfish

k3s_version: v1.27.6+k3s1
token: "asdf"
api_endpoint: "{{ hostvars[groups['server'][0]]['ansible_host'] | default(groups['server'][0]) }}"
extra_server_args: "--tls-san {{ lb_address }} --node-ip {{ hostvars[inventory_hostname].ansible_host }} --disable=traefik --disable=servicelb --disable=local-storage"
extra_agent_args: ""

lb_address: 10.0.1.50
lb_interface: eth0
lb_port: 6440

# Optional vars
# api_port: 6443
# k3s_server_location: /var/lib/rancher/k3s
# systemd_dir: /etc/systemd/system
# extra_service_envs: [ 'ENV_VAR1=VALUE1', 'ENV_VAR2=VALUE2' ]
# Manifests or Airgap should be either full paths or relative to the playbook directory.
# List of locally available manifests to apply to the cluster, useful for PVCs or Traefik modifications.
# extra_manifests: [ '/path/to/manifest1.yaml', '/path/to/manifest2.yaml' ]
# airgap_dir: /tmp/k3s-airgap-images
# user_kubectl: true, by default kubectl is symlinked and configured for use by ansible_user. Set to false to only kubectl via root user.
# server_config_yaml:  |
  # This is now an inner yaml file. Maintain the indentation.
  # YAML here will be placed as the content of /etc/rancher/k3s/config.yaml
  # See https://docs.k3s.io/installation/configuration#configuration-file
