---

#- name: Install k3s 
#  ansible.builtin.shell: |
#    curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --disable=traefik --flannel-backend=host-gw --tls-san=10.0.1.50 --bind-address=10.0.1.50 --advertise-address=10.0.1.50 --node-ip=10.0.1.50 --write-kubeconfig-mode --cluster-init" sh -s -
#  args:
#    executable: /bin/bash

- name: Fetch k3s.yaml from remote host
  ansible.builtin.fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: terraform/k3s.yaml
    flat: yes

- name: Replace 127.0.0.1 with Server (#1) IP in k3s.yaml
  ansible.builtin.replace:
    path: terraform/k3s.yaml
    regexp: '127\.0\.0\.1'
    replace: "{{ hostvars[groups['server'][0]]['ansible_default_ipv4']['address'] }}"
  delegate_to: localhost
  become: false
