---

- name: Install k3s 
  ansible.builtin.shell: |
    curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --disable=traefik --flannel-backend=host-gw --tls-san=10.0.1.50 --bind-address=10.0.1.50 --advertise-address=10.0.1.50 --node-ip=10.0.1.50 --write-kubeconfig-mode --cluster-init" sh -s -
  args:
    executable: /bin/bash

- name: Fetch k3s.yaml from remote host
  ansible.builtin.fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: terraform/k3s.yaml
    flat: yes